spring:

  datasource:
    url: jdbc:postgresql://localhost:15432/dsvendas
    username: postgres
    password: 123456

  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
#        hbm2ddl.delimiter: ;
#      javax.persistence.schema-generation:
#        create-source: metadata
#        scripts:
#          action: create
#          create-target: create.sql
